enum RefferalCodeActionTypeEnum {
    REFFERALCODE_LOADING = "REFFERALCODE_LOADING",
    REFFERALCODE_LOADED = "REFFERALCODE_LOADED",
    GET_ALL_REFFERALCODE = "GET_ALL_REFFERALCODE",
    UPDATE_REFFERALCODE = "UPDATE_REFFERALCODE",
    GET_REFFERALCODE_BY_ID = "GET_REFFERALCODE_BY_ID",
    DELETE_REFFERALCODE = "DELETE_REFFERALCODE",
    ADD_NEW_REFFERALCODE = "ADD_NEW_REFFERALCODE"
}

export default RefferalCodeActionTypeEnum;