enum DriverHandBookActionTypeEnum {
    DRIVERHANDBOOK_LOADING = "DRIVERHANDBOOK_LOADING",
    DRIVERHANDBOOK_LOADED = "DRIVERHANDBOOK_LOADED",

    GET_ALL_DRIVERHANDBOOK = "GET_ALL_DRIVERHANDBOOK",
    GET_DRIVERHANDBOOK_BY_ID = "GET_DRIVERHANDBOOK_BY_ID",
    UPDATE_DRIVERHANDBOOK = "UPDATE_DRIVERHANDBOOK",
    DELETE_DRIVERHANDBOOK = "DELETE_DRIVERHANDBOOK",
    ADD_NEW_DRIVERHANDBOOK = "ADD_NEW_DRIVERHANDBOOK"
}

export default DriverHandBookActionTypeEnum;