enum DriversActionTypeEnum {

  DRIVERS_LOADING = "DRIVERS_LOADING",
  DRIVERS_LOADED = "DRIVERS_LOADED",

  GET_ALL_DRIVERS = "GET_ALL_DRIVERS",
  GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID",
  GET_DRIVER_TIMESLOTS = "GET_DRIVER_TIMESLOTS",

  UPDATE_DRIVER_STATUS = "UPDATE_DRIVER_STATUS",
  DELETE_DRIVER = "DELETE_DRIVER",
}

export default DriversActionTypeEnum;
