export { default as Dashboard } from "./dashboard/dashboard";
export { default as PendingOrders } from "./orders/pending-orders";
export { default as Login } from "./login/login";
export { default as Profile } from "./profile/profile";
export { default as ChangePassword } from "./profile/change-password";
export { default as EditProfile } from "./profile/edit-profile";
export { default as ForgotPassword } from "./forgot-password/forgot-password";
export { default as ViewOrder } from "./orders/view-order";
export { default as OrdersHistory } from "./orders/orders-history";
export { default as Vehicle } from "./vehicle/list";
export { default as View } from "./vehicle/view";
export { default as Form } from "./vehicle/form";
export { default as DriverView } from "./driver/view";
export { default as FormDriver } from "./driver/form";
export { default as AssignTimeslot } from "./driver/assign-timeslot";
export { default as UserView } from "./user/view";
export { default as PromocodeList } from "./promocode/list";
export { default as PromocodeForm } from "./promocode/form";
export { default as Report } from "./report/list";
export { default as PostcodeList} from "./postcode/list"
export { default as FuelTypeList} from "./fueltype/list"
export { default as ReferalCodeList } from "./referalcode/list"
export { default as Timeslot } from "./timeslot/list"
export { default as NoificationList } from "./notification/list"
export { default as Notificationform } from "./notification/form"
export { default as AppSettingsList } from "./app-settings/list"
export { default as EmailList } from "./email-templates/list"
export { default as EmailTemplatesForm } from "./email-templates/form"
export { default as CMSPages } from "./cms/list"
export { default as CMSPagesForm } from "./cms/form"
export { default as CMSPagesView } from "./cms/view"
export { default as CMSPagesContactUs } from "./cms/contact-us"
export { default as SubAdminsList } from "./sub-admins/list"
export { default as RolesPermissionsList } from "./roles-permissions/list"
export { default as RolesPermissionsForm } from "./roles-permissions/form"
export { default as DriverHandbookList } from "./driverhandbook/list"
export { default as GasList } from "./gas/list"
export { default as GasForm } from "./gas/form"
export { default as FuelList } from "./fuel/list"
export { default as FuelForm } from "./fuel/form"
export { default as EarningPages } from "./earnings/list"
export { default as FaqList } from "./faq/list"
export { default as FaqForm } from "./faq/form"
export { default as LocationList } from "./location/list"
export { default as SidebarEarningList } from "./earning/list"
export { default as GeofanceList } from "./geofences/list"
export { default as GeofencesForm } from "./geofences/form"
export { default as VendorsList } from "./vendors/list"
export { default as VendorsForm } from "./vendors/form"
export { default as VendorsView } from "./vendors/view"
export { default as VendorsCategoryList } from "./vendors-category/list"