enum EmailTemplateTypeEnum {
    EMAIL_TEMPLATE_LOADING = "EMAIL_TEMPLATE_LOADING",
    EMAIL_TEMPLATE_LOADED = "EMAIL_TEMPLATE_LOADED",

    GET_EMAIL_TEMPLATE_LIST = "GET_EMAIL_TEMPLATE_LIST",
    UPDATE_EMAIL_TEMPLATE = "UPDATE_EMAIL_TEMPLATE",
    GET_EMAIL_TEMPLATE_BY_ID = "GET_EMAIL_TEMPLATE_BY_ID"
}

export default EmailTemplateTypeEnum;