import { ActionType } from "typesafe - actions";
import * as actions from "./ orders.action";

type TOrderByIdPayload =
  {
    id: number,
    uuid: string,
    address: string,
    city: string,
    state: string,
    country: string,
    lat: number,
    long: number,
    orderType: number,
    qty: number,
    price: number,
    scheduleDate: string,
    startTime: string,
    endTime: string,
    driverStartTime: null | string,
    driverEndTime: null | string,
    fuelQtyDriver: null | string,
    pumpReadingImage: null | string,
    tankCheckComment: null | string,
    subTotal: number,
    grandTotal: number,
    vatPercentage: number,
    vatPrice: number,
    deliveryVatPercentage: number,
    deliveryVatPrice: number,
    deliveryPrice: number,
    adminPercentage: null | number,
    adminReceivedAmount: number,
    refundAmount: null | number,
    priority: number,
    isDelivered: boolean,
    isPaid: boolean,
    isRefunded: boolean,
    promocodeDiscountAmount: null | number,
    promocodeDiscountPercentage: null | number,
    referralDiscountAmount: null | number,
    referralDiscountPercentage: null | number,
    safetyChecks: null | string,
    tankChecks: null | stirng,
    status: string,
    rating: null | number,
    orderFeedback: null | string,
    driverCancellationCharge: null | number,
    customerCancellationCharge: null | number,
    cancellationReasonOther: null | number,
    createdAt: stirng,
    updatedAt: stirng,
    deletedAt: null | stirng,
    createdBy: stirng,
    updatedBy: stirng,
    user: {
      id: stirng,
      fullName: stirng,
      email: stirng,
      countryCode: stirng,
      mobileNumber: number,
      userType: stirng,
      profileImage: null | stirng,
      addresses: null | stirng,
      emailVerify: boolean,
      mobileVerify: boolean,
      firstOrderComplete: boolean,
      referBenefitUsed: boolean,
      referralCode: stirng,
      createdAt: stirng,
      updatedAt: stirng,
      deletedAt: null | stirng,
      createdBy: null | stirng,
      updatedBy: null | stirng,
      isActive: boolean
    },
    driver: {
      id: stirng,
      fullName: stirng,
      email: stirng,
      countryCode: stirng,
      mobileNumber: number,
      userType: stirng,
      profileImage: null | stirng,
      addresses: null | stirng,
      emailVerify: boolean,
      mobileVerify: boolean,
      firstOrderComplete: boolean,
      referBenefitUsed: boolean,
      referralCode: stirng,
      createdAt: stirng,
      updatedAt: stirng,
      deletedAt: null | stirng,
      createdBy: null | stirng,
      updatedBy: null | stirng,
      isActive: boolean
    },
    cancellationReasonId: null | stirng,
    userAddressId: null | string,
    userId: string
  }

type TOrdersFuel = {
  count: number;
  orders: {
    id: number,
    uuid: string,
    address: string,
    city: string,
    state: string,
    country: string,
    lat: number,
    long: number,
    orderType: number,
    qty: number,
    price: number,
    scheduleDate: string,
    startTime: string,
    endTime: string,
    driverStartTime: null | string,
    driverEndTime: null | string,
    fuelQtyDriver: null | number,
    pumpReadingImage: null | string,
    tankCheckComment: null | string,
    subTotal: number,
    grandTotal: number,
    vatPercentage: number,
    vatPrice: number,
    deliveryVatPercentage: number,
    deliveryVatPrice: number,
    deliveryPrice: number,
    adminPercentage: null,
    adminReceivedAmount: number,
    refundAmount: null | number,
    priority: number,
    isDelivered: boolean,
    isPaid: boolean,
    isRefunded: boolean,
    promocodeDiscountAmount: null | number,
    promocodeDiscountPercentage: null | number,
    referralDiscountAmount: null | number,
    referralDiscountPercentage: null | number,
    safetyChecks: null | string,
    tankChecks: null | string,
    status: string,
    rating: null | number,
    orderFeedback: null | string,
    driverCancellationCharge: null | number,
    customerCancellationCharge: null | number,
    cancellationReasonOther: null | number,
    createdAt: string,
    updatedAt: string,
    deletedAt: null | string,
    createdBy: stirng,
    updatedBy: string | null,
    user: {
      id: string,
      fullName: string,
      mobileNumber: number,
      profileImage: null | string,
    },
    driver: {
      id: string,
      fullName: string,
      mobileNumber: number,
      profileImage: null | string,
    },
    cancellationReasonId: null | string,
    userAddressId: null | string,
    userId: string
  }[];
};

type TOrdersGas = {
  count: number,
  orders: {
    id: number,
    uuid: string,
    address: string,
    city: string,
    state: string,
    country: string,
    lat: number,
    long: number,
    orderType: number,
    qty: number,
    price: number,
    scheduleDate: string,
    startTime: string,
    endTime: string,
    driverStartTime: null | string,
    driverEndTime: null | string,
    fuelQtyDriver: null | number,
    pumpReadingImage: null | string,
    tankCheckComment: null | string,
    subTotal: number,
    grandTotal: number,
    vatPercentage: number,
    vatPrice: number,
    deliveryVatPercentage: number,
    deliveryVatPrice: number,
    deliveryPrice: number,
    adminPercentage: null | number,
    adminReceivedAmount: number,
    refundAmount: null | number,
    priority: number,
    isDelivered: boolean,
    isPaid: boolean,
    isRefunded: boolean,
    promocodeDiscountAmount: null | number,
    promocodeDiscountPercentage: null | number,
    referralDiscountAmount: null | number,
    referralDiscountPercentage: null | number,
    safetyChecks: null | stirng,
    tankChecks: null | stirng,
    status: string,
    rating: null | number,
    orderFeedback: null | string,
    driverCancellationCharge: null | number,
    customerCancellationCharge: null | number,
    cancellationReasonOther: null | stirng,
    createdAt: string,
    updatedAt: string,
    deletedAt: null | string,
    createdBy: string,
    updatedBy: string,
    user: {
      id: string,
      fullName: string,
      mobileNumber: number,
      profileImage: null | string
    },
    driver: {
      id: string,
      fullName: string,
      mobileNumber: number,
      profileImage: null | string
    },
    cancellationReasonId: null | string,
    userAddressId: null | string,
    userId: string
  }[]
}

type TRescheduleTimeSlots = {
  id: number | string;
  startTime: string;
  endTime: string;
}[];

type TOrdersState = {
  loading: boolean;
  orderId: string | number;
  orderById: TOrderByIdPayload;
  orderFuelData: TOrdersFuel;
  orderGasData: TOrdersGas;
  rescheduleTimeSlots: TRescheduleTimeSlots;
};

type TOrdersActionType = ActionType<typeof actions>;

export {
  TOrdersActionType,
  TOrdersState,
  TOrdersFuel,
  TOrdersGas,
  TRescheduleTimeSlots,
  TOrderByIdPayload,
};
