enum ReportsActionTypeEnum {
  REPORTS_LOADING = "REPORTS_LOADING",
  REPORTS_LOADED = "REPORTS_LOADED",
  GET_USER_REPORTS = "GET_USER_REPORTS",
  GET_DRIVER_REPORTS = "GET_DRIVER_REPORTS",
  GET_VEHICLE_REPORTS = "GET_VEHICLE_REPORTS",
}

export default ReportsActionTypeEnum;
